export const TRADE_OPTIONS = [
  "General Contracting",
  "Construction Management",
  "Project Management",
  "Electrical",
  "Commercial Electrical",
  "Residential Electrical",
  "Industrial Electrical",
  "Low Voltage",
  "Fire Alarm",
  "Security Systems",
  "Data / Communications",
  "Solar / Renewable Energy",
  "EV Charger Installation",
  "Plumbing",
  "Commercial Plumbing",
  "Residential Plumbing",
  "Pipefitting",
  "Steamfitting",
  "Gas Fitting",
  "HVAC",
  "Heating",
  "Air Conditioning",
  "Refrigeration",
  "Sheet Metal",
  "Controls / Building Automation",
  "Carpentry",
  "Finish Carpentry",
  "Rough Carpentry",
  "Framing",
  "Cabinetry",
  "Millwork",
  "Doors / Hardware",
  "Windows",
  "Drywall",
  "Taping / Finishing",
  "Insulation",
  "Painting",
  "Decorating",
  "Flooring",
  "Tile",
  "Hardwood Flooring",
  "Carpet",
  "Vinyl Flooring",
  "Concrete",
  "Concrete Forming",
  "Concrete Finishing",
  "Rebar",
  "Masonry",
  "Bricklaying",
  "Stonework",
  "Roofing",
  "Metal Roofing",
  "Siding",
  "Cladding",
  "Waterproofing",
  "Foundation Repair",
  "Excavation",
  "Earthworks",
  "Site Work",
  "Grading",
  "Trenching",
  "Demolition",
  "Land Clearing",
  "Paving",
  "Asphalt",
  "Roadwork",
  "Landscaping",
  "Hardscaping",
  "Irrigation",
  "Fencing",
  "Decks / Patios",
  "Structural Steel",
  "Steel Erection",
  "Welding",
  "Metal Fabrication",
  "Ornamental Iron",
  "Scaffolding",
  "Rigging",
  "Crane Services",
  "Heavy Equipment",
  "Equipment Rental",
  "Glazing",
  "Curtain Wall",
  "Storefront",
  "Elevators",
  "Escalators",
  "Fire Protection",
  "Sprinkler Systems",
  "Firestopping",
  "Acoustical Ceilings",
  "Specialty Ceilings",
  "Kitchen Installation",
  "Bathroom Renovation",
  "Renovation / Remodeling",
  "Restoration",
  "Water Damage Restoration",
  "Fire Damage Restoration",
  "Mold Remediation",
  "Asbestos Abatement",
  "Environmental Services",
  "Surveying",
  "Civil Engineering",
  "Structural Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Architecture",
  "Interior Design",
  "Estimating",
  "Quantity Surveying",
  "Inspection",
  "Quality Control",
  "Safety",
  "Commissioning",
  "Testing / Balancing",
  "Cleaning",
  "Final Cleaning",
  "Waste Removal",
  "Snow Removal",
  "Property Maintenance",
  "Facility Maintenance",
  "Handyman",
  "Pool / Spa",
  "Marine Construction",
  "Telecommunications",
  "Utility Work",
  "Other",
] as const;
